### ISSUE TITLE
jspsychr

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/rparp#4]
https://github.com/mvuorre/rparp/blob/32240089c7fffb38f3ca31496312580a90694b63/manuscript/manuscript.Rmd#L119

We can certainly mention jspsychr, but I fear that it adds unnecessary complexity to the user, but also to the maintainer of jspsychr. Every time jspsych updates with new stuff, I think jspsychr also needs to update the code to include it, right? 

Also, those lines in the MS suggest that you can't create a jsPsych html experiment with RStudio, which is not accurate. I'm going to suggest some changes to this passage shortly.

Edit: This definitely reflects my laziness in not learning what jspsychr is and how it works. But that seems to suggest that an extra step of learning / complexity is required from users, so suggesting it to new users may be counterproductive.

**Comment by CrumpLab** [comment]
Good idea to clarify that RStudio can be used to write jspsych experiments directly. 

As far as jspsychr I guess I'm partial to keeping a minimal mention of it in the manuscript as an option.

Overall, I agree that it adds complexity. It certainly does right now in terms of managing installation of the jspsych library. I made changes to the `init_jspsych()` so that it also loads the `jspsychr()` template, which I'll refactor. Right now both get loaded, so the library gets stored in two places. 

It would be better to break apart those options. For simplicity, we can go back to what you had before, with `init_jspsych()` downloading the library and creating an experiment directory with the hello world example. I'll add a separate `init_jspsychr()` option, and for now keep it out of the main creation file. Instead, I'll mention the option in the getting started tutorial, along with the current issue of making sure the jspsych library is up to date. I need to find some way of solving that problem on the jspsychr end.

jspsychr has some nice features like running the experiment locally from RStudio using plumber, but I think you're right that if jspsych is complicated, then jspsychr is more complicated. At the same time, I'm hoping that some of the tutorials on jspsychr might be helpful for motivating people to try out jspsych in general, so jspsychr could potentially play pedagogical role.

**Comment by CrumpLab** [comment]
I just pushed a fix to vertical master. `init_jspsych()` is back to the way it was, and does not load `jspsychr`. One exception is that I put `experiment.html` into `inst/templates` so that I could use `usethis::use_template()` to load the template, this method seems to respect the file paths better.

In general it seems that the template folder is a better strategy, we could probably delete `inst/vertical`, as it is now redundant with `inst/templates`, and `inst/templates` seems like a better approach to stay consistent with usethis. 

Also, there is a new `init_jspsychr()`, but it's not added an option during creation, just an option after installation. It seems better to keep this function in limbo this way until I figure out handling the jspsych library issue.

**Comment by mvuorre** [comment]
I think it is good as it is now.
